config/routes.rb
Rails.application.routes.draw do
  resources :tools
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :most_recent_tool

  def most_recent_tool
    Tool.find(session[:most_recent_tool_id])
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
    @tools = Tool.all
  end

  def show
    @tool = Tool.find(params[:id])

  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save
      binding.pry
      session[:most_recent_tool_id] = @tool.id
      flash[:notice] = "Tool Created Successfully"
      redirect_to tool_path(@tool)
    else
      flash.now[:error] = @tool.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update(tool_params)
      redirect_to tool_path(@tool)
    else
      render :edit
    end
  end

  def destroy
    @tool = Tool.find(params[:id])
    @tool.destroy
    redirect_to tools_path
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :price, :quantity)
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, msg|  %>
    <%= content_tag :div, msg, class: "flash_#{type}" %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/shared/_tools.html.erb
<%= form_for(@tool) do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %><br>
  <%= f.label :price, "Price" %>
  <%= f.text_field :price %><br>
  <%= f.label :quantity %>
  <%= f.text_field :quantity%><br>
  <%= f.submit%>
<% end %>

app/views/tools/edit.html.erb
<%= render "shared/tools", locals: {tool: @tool}%>

app/views/tools/index.html.erb
<% @tools.each do |tool| %>
  <%= link_to tool.name, tool_path(tool) %><br>
<% end %>
<%= link_to "New Tool", new_tool_path%>

app/views/tools/new.html.erb
<%= render "shared/tools", locals: {tool: @tool}%>

app/views/tools/show.html.erb
<div class="tool_info">
  <ul>
    <li><%= @tool.name %> </li>
    <li>$<%= @tool.price %></li>
    <li>InStock: <%= @tool.quantity %></li>
  </ul>
</div>
<%= link_to "Edit", edit_tool_path(@tool)%>
<%= link_to "Delete", tool_path(@tool), method: :delete %>